[package]
name = "digits_pi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "digits_pi"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
